### ISSUE TITLE
can't add integration from gui

### ISSUE THREAD

**Issue by gazsoimi** [greenhess/adap1meter#2]
hy.

To configure the integration:

1.    Go to Settings > Devices & Services > Add Integration.
 2.   Search for "ADA P1 Meter" and enter the connection details (e.g., hostname and port).
 3.   The integration will create sensors for each available measurement from the meter.

szóval, ha jól értem a 2. lépés alapján gui-ból kéne, hogy tudjam megadni az eszköz elérését, portját.

viszont nem engedi, azt írja, csináljam a configból.

![kép](https://github.com/user-attachments/assets/ecabcaf4-0be9-4827-9b92-054ed951542f)

itt a zip fájlban talált config mintát megróbáltam bemásolni, meg is jelennek entitások, de üresek.
https://greenhess.com/ada12-home-assistant-integracio

a dologhoz hozzá tartozik, hogy külön vlan-on van, nincs dns feloldás. 

a __init__ fájlban átírtam az elérést az ip-re.

**Comment by gazsoimi** [comment]
egyébként az mqtt-n enélkül is elindul valami, mert egy dsmr reader integráció talál 82 új entitást, de mind üres.

**Comment by amaximus** [comment]
Szia,

mint azt írtam Veres Tamás kollégádnak, vagy config_flow-t adtok hozzá vagy
yaml-ban kell konfigurálni.
Az üzenet csak azért van mert a Home Assistant hivatalosan a config_flow-os
megoldást nyomatja, de ettől függetlenül a régi, yaml-osat is támogatja a
custom integrációk esetén (a core-nál nem).

üdv Attila

**Comment by gazsoimi** [comment]
na, játszadoztam.

configba csak ennyit kell hozzáadni:

**Comment by greenhess** [comment]
Üdv! 

Még egy kicsit fejlesztjük az integrációt. A leírásban olvasható az régi linuxok mDNS feloldási problémája ez most egyszerűen módosítható. (https://github.com/greenhess/adap1meter/blob/main/README.md) Ami nincs leírva, hogy sajnos még nem kerül be a configuration.yaml fájlba az "ada12:" bejegyzés ezt manuálisan be kell másolni. 

![adaconf](https://github.com/user-attachments/assets/5293b61d-8aa2-4d5e-9db3-aef1d4e4298e)


**A weboldalon írtam erről:**
Megjegyzés: Ha a HACS-ban nem találod az „ADA P1 Meter” integrációt, akkor manuálisan is hozzáadhatod a GitHub hivatkozást. Ehhez kövesd az alábbi lépéseket:

    Nyisd meg a Home Assistant felületét, majd menj a HACS menüpontra.
    A HACS jobb felső sarkában kattints a menü ikonra (három pont), majd válaszd a Custom repositories lehetőséget.
    A megjelenő mezőbe írd be az ADA P1 Meter GitHub hivatkozását https://github.com/greenhess/adap1meter, majd válaszd ki az "Integration" típusú elemet.
    Végül kattints az Add gombra, és az integráció már elérhető lesz a HACS-ban.

**Comment by greenhess** [comment]
> na, játszadoztam.
> 
> configba csak ennyit kell hozzáadni:
> 
> sensor:
> 
>     * platform: ada12
> 
> 
> így megy.
> 
> másik észrevétel, a [http://okosvillanyora.local:8989/json](http://10.90.93.12:8989/json) címen a json-ban az első 2 mező az mqtt szerver felhasználóneve, és jelszava.
> 
> biztos best practice egy jelszót kirakni egy sima jsonba?
> 
> @amaximus amaximus , a válasz gondolom a repo gazdának szólt, és nem nekem, én nem ismerek semmilyen Veres Tamást.

Üdv, javaslom a HACS verziót, mert ott több entitás elő van készítve... A DSMR integráció nem lesz kompatibilis mert a villanyórák telegram dsmr adatai pont nem így néznek ki :)

**Comment by greenhess** [comment]
**Sziasztok, elkészül az v1.2.9-nél tartok. ez most jónak tűnik már van host és port beállítás is és nem szükséges az "ada12:" bejegyzés sem a configuration.yaml-ba.**
